default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: workout_development

test:
  <<: *default
  database: workout_test

production:
  <<: *default
  username: <%= ENV['WORKOUT_DATABASE_USER'] %>
  password: <%= ENV['WORKOUT_DATABASE_PASS'] %>