default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: workout_development

test:
  <<: *default
  adapter: sqlite3
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  database: workout
  username: <%= ENV['WORKOUT_DATABASE_USER'] %>
  password: <%= ENV['WORKOUT_DATABASE_PASS'] %>